# Generated by Django 5.1 on 2024-08-22 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_path', models.CharField(max_length=30, unique=True)),
                ('full_path', models.TextField(default='')),
                ('link_desc', models.CharField(blank=True, default='', help_text='link description', max_length=100)),
                ('is_auto_invalid', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0, help_text='open auto invalid')),
                ('invalid_after_time', models.DateTimeField(blank=True, help_text='invalid after this time', null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='create time', null=True)),
                ('update_time', models.DateTimeField(auto_now=True, help_text='update time', null=True)),
                ('is_deleted', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0, help_text='is marked as deleted')),
            ],
        ),
        migrations.CreateModel(
            name='AccessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, help_text='Visit time')),
                ('source_ip', models.CharField(max_length=50)),
                ('source_ip_country', models.CharField(max_length=100)),
                ('source_ip_city', models.CharField(max_length=100)),
                ('referer', models.TextField()),
                ('referer_domain', models.CharField(max_length=100)),
                ('user_agent', models.TextField()),
                ('user_agent_device', models.CharField(max_length=200)),
                ('user_agent_os', models.CharField(max_length=200)),
                ('user_agent_browser', models.CharField(max_length=200)),
                ('url', models.ForeignKey(help_text='Short url', on_delete=django.db.models.deletion.CASCADE, to='core.shorturl')),
            ],
        ),
    ]
